# modules/rt-audio-riscv.nix — RT kernel + audio subsystem (RISC-V / JH7110)
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025-2026 DeMoD LLC.
#
# RISC-V counterpart to the x86 CachyOS RT path. The CachyOS RT BORE kernel
# does not build for riscv64; instead we use mainline Linux 6.12 LTS and
# explicitly enable native PREEMPT_RT, which was merged upstream in 6.12.
# x86-specific boot parameters (intel_idle, TSC clocksource, mitigations)
# are dropped; everything here is architecture-neutral RT tuning.

{ config, lib, pkgs, musnix ? null, ... }:

with lib;

let
  # Linux 6.12 is the production baseline for JH7110 RT audio: recent enough
  # for native PREEMPT_RT, less volatile than linuxPackages_latest.
  baseRtKernelPackages =
    if pkgs ? linuxPackages_6_12
    then pkgs.linuxPackages_6_12
    else pkgs.linuxPackages_latest;

  nativeRtKernelConfig = with lib.kernel; {
    EXPERT = yes;
    PREEMPT_RT = yes;
    RT_GROUP_SCHED = no;
    PREEMPT_VOLUNTARY = mkForce no;
  };

  nativeRtKernelPackages = pkgs.linuxPackagesFor (
    baseRtKernelPackages.kernel.override {
      structuredExtraConfig = nativeRtKernelConfig;
      ignoreConfigErrors = true;
    }
  );

  musnixPackage =
    path:
      if musnix != null
      then pkgs.callPackage "${musnix}/${path}" {}
      else null;

  rtcqsPackage = musnixPackage "pkgs/rtcqs.nix";
  rtirqPackage = musnixPackage "pkgs/os-specific/linux/rtirq";

  rtirqConf = pkgs.writeText "rtirq.conf" ''
    # Generated by modules/rt-audio-riscv.nix.
    RTIRQ_NAME_LIST="snd usb xhci"
    RTIRQ_PRIO_HIGH=90
    RTIRQ_PRIO_DECR=5
    RTIRQ_PRIO_LOW=51
    RTIRQ_RESET_ALL=0
    RTIRQ_NON_THREADED="rtc snd"
  '';
in
{
  # ── Kernel ──────────────────────────────────────────────────────
  assertions = [
    {
      assertion = versionAtLeast baseRtKernelPackages.kernel.version "6.12";
      message = "RISC-V RT audio requires Linux >= 6.12 for native PREEMPT_RT";
    }
  ];

  # Mainline Linux 6.12+ with CONFIG_PREEMPT_RT=y, mirroring musnix's native
  # RT path without importing its currently incompatible nixpkgs overlay.
  boot.kernelPackages = mkDefault nativeRtKernelPackages;

  # ── Kernel Parameters (architecture-neutral RT tuning) ─────────
  boot.kernelParams = [
    # Isolate cores 2-3 for RT workloads
    "isolcpus=managed_irq,domain,2-3"

    # Full tickless on isolated cores
    "nohz_full=2-3"

    # RCU callback offloading
    "rcu_nocbs=2-3"
    "rcu_nocb_poll"

    # Steer all IRQs to non-isolated cores
    "irqaffinity=0,1"
    "kthread_cpus=0,1"

    # Disable watchdogs
    "nmi_watchdog=0"
    "nosoftlockup"

    # Offset tick timers across cores
    "skew_tick=1"

    # Threaded IRQ handlers (required for PREEMPT_RT)
    "threadirqs"
  ];

  # ── Kernel Sysctl (architecture-neutral) ────────────────────────
  boot.kernel.sysctl = {
    "kernel.sched_rt_runtime_us" = -1;
    "vm.stat_interval" = 120;
    "kernel.sched_rt_period_us" = 1000000;
    "vm.dirty_writeback_centisecs" = 1500;
    "kernel.randomize_va_space" = 0;
  };

  # ── Power Management ────────────────────────────────────────────
  # JH7110 uses the generic cpufreq framework.
  powerManagement.cpuFreqGovernor = "performance";

  services.power-profiles-daemon.enable = false;
  services.thermald.enable = false;

  # ── IRQ Balance ─────────────────────────────────────────────────
  services.irqbalance.enable = false;

  # ── Kernel Modules ──────────────────────────────────────────────
  boot.kernelModules = [
    "i2c-dev"
    "snd-usb-audio"
  ];

  # ── RT Tooling ──────────────────────────────────────────────────
  # We use musnix's packaged rtcqs/rtirq artifacts, but do not import
  # musnix.nixosModules.musnix because its overlay still references removed
  # legacy RT patch attributes in the locked nixpkgs.
  environment.systemPackages =
    optional (rtcqsPackage != null) rtcqsPackage
    ++ optional (rtirqPackage != null) rtirqPackage;

  environment.etc."rtirq.conf" = mkIf (rtirqPackage != null) {
    source = rtirqConf;
  };

  systemd.services.rtirq = mkIf (rtirqPackage != null) {
    description = "IRQ thread tuning for realtime kernels";
    after = [ "multi-user.target" "sound.target" ];
    wantedBy = [ "multi-user.target" ];
    path = with pkgs; [
      gawk
      gnugrep
      gnused
      procps
    ];
    serviceConfig = {
      User = "root";
      Type = "oneshot";
      ExecStart = "${rtirqPackage}/bin/rtirq start";
      ExecStop = "${rtirqPackage}/bin/rtirq stop";
      RemainAfterExit = true;
    };
  };
}
