# DO NOT EDIT this file manually! It is generated by nixos-generate-config.
# Place your actual generated content here during installation.
# This is a placeholder example.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/your-root-uuid";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/your-boot-uuid";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/your-swap-uuid"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking,
  # the default behaviour is to use dhcpcd as DHCP client.
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
